name: Publish

on:
  push:
    tags:
      - '*'
  
jobs:

  build:
    name: Build binary
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install libpcap
      run: sudo apt install -y libpcap-dev --install-suggests

    - name: Get dependencies
      run:  go get -v 
      working-directory: "."

    - name: Build
      run: go build -o gopherCap .
      working-directory: "./"

    - uses: actions/upload-artifact@v2
      with:
        name: gopherCap
        path: ./gopherCap

    - name: Upload Linux binary to release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./gopherCap
        asset_name: gopherCap
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
